nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml

The features that define which target is chosen is always required,
independently of whether the `rt` feature is enabled.

Unconditionally enable nrf52-hal-common features

---

nrf52-hal-common/src/gpio.rs

Due to the way that the svd codegen works, the P1 types are emitted
into the p0 module in the peripheral crate, so we need to add a
parameter to the macro to distinguish between the source module and
the exported module; I'm choosing to emit the P1 pins in a p1 module
rather than also jamming them into the p0 module in the hal.

Add support for GPIO P1 on nrf52840

---

nrf52-hal-common/src/timer.rs

Previously, calling the `start` method while the timer was already
running had no effect, and the `cycles` argument was ignored. Now it
effectively restarts the timer.

Clear counter value when starting timer

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/rng.rs

I've only tested this on an nRF52832, but since it compiles, I assume it'll work on nRF52840, too.

Add interface to RNG peripheral

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/uarte.rs
nrf52832-hal/src/lib.rs

Some boards, such as the DWM1001-DEV, have this wired up to the on-board debugger, and is useful for outputting debug information.
This is based heavily on the SPIM driver

Add TX-only uarte0

---

nrf52-hal-common/src/rng.rs
nrf52-hal-common/src/spim.rs
nrf52-hal-common/src/twim.rs
nrf52-hal-common/src/uarte.rs

Hey all,
This change introduces two major things:
* Uses an `AcqRel` compiler fence before the end of each driver function that invokes DMA, to prevent misoptimization
* Adds my `write_read` interface to TWIM, useful for I2C devices that implement a typical register interface (write address/subaddress, then read data)
The target for this merge is the re-release branch.
Closes https://github.com/nrf-rs/nrf52-hal/issues/33 - at least hopefully.

Conservative fences

---

.cargo/config
.travis.yml
boards/adafruit_nrf52pro/Cargo.toml
boards/adafruit_nrf52pro/examples/blinky.rs
boards/adafruit_nrf52pro/src/lib.rs
nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/clocks.rs
nrf52-hal-common/src/delay.rs
nrf52-hal-common/src/gpio.rs
nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/rng.rs
nrf52-hal-common/src/spim.rs
nrf52-hal-common/src/timer.rs
nrf52-hal-common/src/twim.rs
nrf52-hal-common/src/uarte.rs
nrf52832-hal/Cargo.toml
nrf52832-hal/Xargo.toml
nrf52832-hal/build.rs
nrf52832-hal/memory.x
nrf52832-hal/src/lib.rs
nrf52840-hal/Cargo.toml
nrf52840-hal/memory.x
nrf52840-hal/src/lib.rs

* Update for 2018 edition
* Harmonize versions to 0.6.0-beta.1, matching -pac crates
* Update dependencies
* Massage some differences between 832 and 840 to be more consistent
* Remove Xargo.toml from 840
* Update my email address
All PRs in this family:
* [nrf52832-pac]
* [nrf52840-pac]
* [nrf52-hal]
[nrf52832-pac]: https://github.com/nrf-rs/nrf52832-pac/pull/11
[nrf52840-pac]: https://github.com/nrf-rs/nrf52840-pac/pull/2
[nrf52-hal]: https://github.com/nrf-rs/nrf52-hal/pull/32

Changes for the next release, detailed list of changes:

---

nrf52-hal-common/src/gpio.rs

It looked like this was prepared already, I needed to enable a pull up on my gpio so I implemented it.
Pull up is verified on nrf52dk button1 - 4
The pull-down is still untested it is however symmetrical.
Should the function names be different? 
Please enjoy.

Implement pulldown and pullup on input

---

nrf52-hal-common/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml

Issuing a point release to include the support for pullups for GPIOs.
NB: I have changed the dependencies in the `nrf528xx-hal` crates to use an **exact** dependency on the `nrf52-hal-common` crate. I do not believe there would be a case where you would ever want the `-hal` and `-hal-common` to differ, so this matches the "works as expected" case IMO.

Version 0.6.1 Release

---

nrf52-hal-common/src/spim.rs

In some scenarios it is possible to setup unidirectional SPI
communication. When only one way communication is needed there
is no need to connect a GPIO for the unused MISO/MOSI pin.
Encoding pins in an Option<Pin> will support this use case

Option encapsulation for SPI Pins

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/spim.rs
nrf52-hal-common/src/twim.rs
nrf52-hal-common/src/uarte.rs

Expose const function in nrf52-hal-common which per platform
return limit of EasyDMA.
Closes #17

Allow larger EasyDMA buffer sizes on nrf52840

---

nrf52832-hal/Cargo.toml
nrf52832-hal/build.rs
nrf52832-hal/memory_xxAA.x
nrf52832-hal/memory_xxAB.x

Properly size the memory variants of the nrf53832 

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/spim.rs

Implement embedded_hal traits and refactor SPIM
Implements spi::blocking::Transfer trait (as first posted in #39 ) with refactoring of other methods to use shared helper function.
Implements spi::blocking::write. - This function is could be called with buffer in flash, copy to ram function is also implemented.
implements #10
implements #37 for SPIM
partially solves #11

Implemenet embedded_hal traits for SPI

---

.travis.yml
Cargo.toml
examples/rtfm-demo/Cargo.toml
examples/rtfm-demo/src/main.rs
nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/gpio.rs
nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/spim.rs
nrf52-hal-common/src/timer.rs
nrf52-hal-common/src/twim.rs
nrf52810-hal/Cargo.toml
nrf52810-hal/build.rs
nrf52810-hal/memory.x
nrf52810-hal/src/lib.rs

This PR adds support for the nRF52810 microcontroller. Since it modifies the common crate, testing with all 3 microcontrollers in the series should be completed before it is merged.
I was unsure of what version to make the `nrf52810-pac` and `nrf52810-hal` crates, and if merged, transferring ownership of `nrf52810-pac` to the `nrf-rs` organisation should be done too.

feat: add nrf52810

---

boards/nRF52840-DK/Cargo.toml
examples/rtfm-demo/Cargo.toml
nrf52-hal-common/Cargo.toml
nrf52810-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml

I'd like to publish new crates.io versions of all HAL crates. Or more specifically, I'd like to publish version 0.7.0 of `nrf52832-hal`, as that's blocking my progress downstream, but releasing all the others as well seem like the right thing to do.
I know that there is some [ongoing controvery](https://github.com/nrf-rs/nrf52-hal/issues/37), as well as some open pull requests. I'd still like to get this out now, as there have been many improvements (some of which I need to publish my [`dwm1001` crate](https://github.com/braun-robotics/rust-dwm1001)). If more things get merged soon, we can publish more versions as required.
Anyone opposed to doing this release right now?
cc @nrf-rs/nrf52

Release version 0.7.0 of all HAL crates

---

README.md

Add reference manual links to the README

---

boards/nRF52840-DK/src/lib.rs
nrf52-hal-common/src/spim.rs

This PR allows the configuration of the frequency, mode and over-read character of the SPIM interfaces.

feat: SPIM configuration

---

nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/rng.rs

This PR implements rand's `RngCore` trait for `Rng`. This will not have an additional cost for those depending on the HAL, but does allow generic drivers and libraries. The embedded-hal `rng::Read` trait is not final and is currently feature-gated, while `RngCore` has more widespread adoption.

Implement rand::RngCore for Rng

---

nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/rng.rs

Follow up to https://github.com/nrf-rs/nrf52-hal/pull/69; I should've used `rand_core` and not `rand` as it pulls in unneeded code, from the docs: "This crate is mainly of interest to crates publishing implementations of RngCore".
This PR fixes that, and additionally uses the `CryptoRng` marker trait to indicate that the RNG is safe to use for cryptographic purposes (as described in the data sheets).

fix: switch to rand_core and mark `Rng` with `CryptoRng`

---

.travis.yml

As opposed to #71, this disables caching completely. This is meant as a baseline comparison.

No cache at all!

---

.travis.yml
Cargo.toml
examples/spi-demo/.cargo/config
examples/spi-demo/Cargo.toml
examples/spi-demo/README.md
examples/spi-demo/src/main.rs

SPIM demonstation code.
Connect a resistor between pin 22 and 23 on to feed MOSI direct back to MISO
If all tests Led1 to 4 will light up, in case of error only the failing test
case will light up.
Pin     Connecton   
P0.24   SPIclk
P0.23   MOSI
P0.22   MISO
This is designed for nRF52-DK board:
https://www.nordicsemi.com/Software-and-Tools/Development-Kits/nRF52-DK
This PR is based on #48 comments on main implementation should be tracked there. This should track the example implementation.

SPI Demo code

---

.travis.yml
Cargo.toml
examples/twi-ssd1306/.cargo/config
examples/twi-ssd1306/.gdbinit
examples/twi-ssd1306/Cargo.toml
examples/twi-ssd1306/README.md
examples/twi-ssd1306/src/main.rs
nrf52-hal-common/src/twim.rs

I was trying to use the Twin strut with other crates that use the i2c traits defined in embedded_hal (embedded_graphics) and I found that Twin was not implementing such traits.
This PR adds the trait implementations linking the logic to the existing functions in the default implementation of th eTwin strut. I didn't move the code to the trait implementation because I was not sure if it would break existing code, but I think this would be the right thing to do.
This PR also adds a new example using the TWI peripheral to use an I2C device. The example only uses the write mechanism.
I would like to add more examples using I2C but I do not have any devices I can use to test atm.
If choose to accept this PR, I would like to clarify if the current implementation of the traits is the right …

Add embedded_hal::blocking::i2c trait implementation

---

.travis.yml
Cargo.toml
boards/nRF52-DK/Cargo.toml
boards/nRF52-DK/README.md
boards/nRF52-DK/examples/blinky.rs
boards/nRF52-DK/src/lib.rs

Adds the board support crate for the Nordic nRF52-DK
https://www.nordicsemi.com/Software-and-Tools/Development-Kits/nRF52-DK
The code follows the same structure as the nRF52840-DK BSC but using the pin configuration for the nRF52-DK
Datasheet:
http://infocenter.nordicsemi.com/pdf/nRF52_DK_User_Guide_v1.2.pdf

Add nRF52-DK board support crate

---

.travis.yml
nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/saadc.rs
nrf52810-hal/src/lib.rs
nrf52832-hal/src/lib.rs
nrf52840-hal/src/lib.rs

Initial PR for my SAADC work, there are still a few things I need some advice/input on.
- Reading VDD (Probably make a unit struct and implement channel for it)
- Configuration is currently hardcoded with reasonable values, how should this be configured?
- Only a single channel is utilised, and only one AIN can be read at a time, how should multiple be used? What about configurations for multiple values? How will values be returned when the sample task ends?
- Calibration is probably not implemented correctly, make it optional when all the channels are known at creation?
- Abuse of the `Channel` trait, any analog input can be connected to any channel's negative or positive side, this isn't well reflected in the current implementation
Squashing all the commits might also be a good idea, I …

SAADC Implementation

---

nrf52832-hal/src/lib.rs

These statements were coming in from `pub use nrf52_hal_common::prelude::*` anyway, so this is just cutting down some code duplication.

Remove redundant pub use statements from nrf52832_hal::prelude.

---

Cargo.toml
boards/adafruit-nrf52-bluefruit-le/Cargo.toml
boards/adafruit-nrf52-bluefruit-le/README.md
boards/adafruit-nrf52-bluefruit-le/build.rs
boards/adafruit-nrf52-bluefruit-le/examples/blinky.rs
boards/adafruit-nrf52-bluefruit-le/memory.x
boards/adafruit-nrf52-bluefruit-le/src/lib.rs

This was basically culled from boards/adafruit_nrf52pro. I added a 'cdc' to the board, for the USB/UARTE0 output and wired up the NFC pins.
The example compiles and runs successfully on my board. I am unable to test NFC functionality directly, but the pins should match the board documentation (such as it is from adafruit).
The memory layout assumes you've got the s132 6.1.1 SoftDevice installed on it from the adafruit bootloader, and is required for the `adafruit-nrfutil` to work. I don't have a j-link, and the board itself is kind of a pain to set up with one, so that's what I have to use. The README has instructions for how to get it all loaded.

Add board support crate for Adafruit's nrf52832 Bluefruit LE board.

---

boards/nRF52-DK/Cargo.toml
boards/nRF52840-DK/Cargo.toml
examples/rtfm-demo/Cargo.toml
examples/spi-demo/Cargo.toml
examples/twi-ssd1306/Cargo.toml
nrf52-hal-common/Cargo.toml
nrf52810-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml

Note: the 810-hal beta has not yet been published due to #91.
CC @nrf-rs/nrf52 @bjc 
If there are no complaints in the next 24 hours or so, I will plan to release this as-is (after removing the `-beta1` suffix)

Commit with pre-release

---

nrf52810-hal/Cargo.toml

An angle bracket missing from the author list means it does not render correctly on crates.io

fix: author list

---

nrf52-hal-common/src/timer.rs

This requires a newer embedded-hal than the one currently being used. Will be safe to merge when embedded-hal has a new release with the timer::Cancel trait.

Add timer cancel

---

nrf52-hal-common/src/uarte.rs

In the `Uarte::read_timeout` method, if the read completes at the same
time that the timeout would occur, a timeout error is thrown, even
though the read is already complete.
This commit changes this behavior, to not do that instead.

Only return timeout error, if receive not complete

---

nrf52-hal-common/src/lib.rs

The timer instance is missing, which caused errors when I tried to fix the dwm1001 crate

Fixed missing export

---

nrf52-hal-common/src/clocks.rs

With the new interface, it seems that the type checker gets confused by constructors with fully generic parameters, even when the return type is certain.
Given the following code:
```rust
// Start the clocks
let _clocks: Clocks<ExternalOscillator, ExternalOscillator, LfOscStarted> = Clocks::new(device.CLOCK)
.enable_ext_hfosc()
.set_lfclk_src_external(LfOscConfiguration::NoExternalNoBypass)
.start_lfclk();
```
I get the error:
```
error[E0282]: type annotations needed
--> nodes/alarm-clock/src/main.rs:155:85
|
155 |         let _clocks: Clocks<ExternalOscillator, ExternalOscillator, LfOscStarted> = Clocks::new(device.CLOCK)
|                                                                                     ^^^^^^^^^^^ cannot infer type for `H`
```
This still fails with the same error …

Help the type checker out

---

nrf52-hal-common/src/rtc.rs
nrf52-hal-common/src/timer.rs

Semi-reverts https://github.com/nrf-rs/nrf52-hal/pull/95.
This updates the interfaces to be compatible with RTFM. RTFM does not give the user code access to the NVIC, and enables interrupts automatically.
I suggest we maintain this pattern moving forward for peripherals that have their own interrupt enable bits.
CC @hannobraun @bjc

Update to be compatible with RTFM

---

nrf52-hal-common/src/uarte.rs

This is mentioned in the datasheet in §4.2 Table 3 (Instantiation
Table) and exists in the PAC for this chipset.
Tested with a nrf52840-mdk board.

Enable UARTE1 for 52840 MCUs.

---

nrf52-hal-common/src/timer.rs
nrf52-hal-common/src/uarte.rs

In response to #115, I have implemented 2 new types: `OneShotTimer` and `PeriodicTimer`. Additionally, backwards compatibility with `Timer` is maintained.
In order to create a new `OneShotTimer`, there are 3 options:
``` Rust
// Same as before
let timer = Timer::new(p.TIMER0);
// More explicitly
let timer = OneShotTimer::new(p.TIMER0);
// or
let timer = PeriodicTimer::new(p.TIMER0).into_oneshot();
```
In order to create a new `PeriodicTimer`, there are 2 options:
```Rust
let timer = PeriodicTimer::new(p.TIMER0);
// or
let timer = Timer::new(p.TIMER0).into_periodic();
```
Conversion between a `OneShotTimer` and a `PeriodicTimer` is facilitated by the functions `into_oneshot()` and `into_periodic()`:
``` Rust
let oneshot_timer = PeriodicTimer::new(p.TIMER0).into_oneshot();
let …
```

Periodic timer

---

boards/actinius-icarus/src/lib.rs
nrf52-hal-common/src/saadc.rs

* nRF9160 has ADC0..7 on pins 13 through 20.
* The ADC returns a signed value.
* The Actinius Icarus puts battery voltage on A0 (P0_13)
* You need the fields of SaadcConfig to be public, otherwise no-one can change them...
I haven't verified whether the pin/channel mapping for non-9160 devices is correct - I just left that as-is.

Fix support for SAADC on nRF9160

---

boards/adafruit_nrf52pro/examples/blinky.rs
boards/adafruit_nrf52pro/src/lib.rs
boards/nRF52-DK/src/lib.rs
boards/nRF52840-DK/src/lib.rs
examples/spi-demo/src/main.rs
examples/twi-ssd1306/src/main.rs
nrf52810-hal/src/lib.rs
nrf52832-hal/src/lib.rs
nrf52840-hal/src/lib.rs

This was already being done in the `nrf9160-hal` and it's also done like that by many (all?) of the STM32 HAL crates.
This is a breaking change.

Re-export PAC crates as `pac`

---

boards/actinius-icarus/Cargo.toml
boards/adafruit-nrf52-bluefruit-le/Cargo.toml
boards/adafruit_nrf52pro/Cargo.toml
boards/nRF52-DK/Cargo.toml
boards/nRF52840-DK/Cargo.toml
boards/nRF9160-DK/Cargo.toml
examples/rtfm-demo/Cargo.toml
examples/spi-demo/Cargo.toml
examples/twi-ssd1306/Cargo.toml
nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/gpio.rs
nrf52-hal-common/src/saadc.rs
nrf52-hal-common/src/spim.rs
nrf52-hal-common/src/timer.rs
nrf52-hal-common/src/twim.rs
nrf52-hal-common/src/uarte.rs
nrf52810-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml
nrf9160-hal/Cargo.toml

Bump PAC and minor dependencies and fix code for 0.9 release.
NOTE: `TIMER3` and `TIMER4` of the `nrf528*` MCUs now have separate `RegisterBlock` types and cannot be unified. I just commented them out for now, a better solution is welcome.

update hals for 0.9.0 (0.2.0) release

---

nrf52-hal-common/src/timer.rs

This was a soundness hole, since unmasking an interrupt in the NVIC is unsafe.
Closes https://github.com/nrf-rs/nrf52-hal/pull/123

Remove NVIC from timer interrupt methods

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/uicr.rs

Adds a basic erase/store/load UICR abstraction for accessing the 32 `customer` registers on `nrf528**` MCUs.

add customer UICR registers abstraction

---

nrf-hal-common/src/gpio.rs
nrf-hal-common/src/spi.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/twi.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/uart.rs
nrf-hal-common/src/uarte.rs

Fixes #146
This compacts the generic `Pin` struct to a single byte on all MCUs, encoding the port in the upper bit.
Breaking change.

Clean up gpio.rs

---

nrf-hal-common/src/spim.rs

This seems to be a classic case of comment vs code. Both iterators are finished if both of them return None, not one of them.
Maybe Closes #156

Fix incorrect logic in transfer_split_uneven

---

nrf-hal-common/src/lib.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/twim.rs

Twim: Implicitly copy buffer into RAM if needed when using embedded hal traits

---

nrf-hal-common/src/rtc.rs

Expose missing tasks of the RTC, according to: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52832.ps.v1.1%2Frtc.html

Add methods for task clear and trigger overflow to the RTC

---

nrf-hal-common/src/twim.rs

Twim would hang if writing or reading if no slave ACKs the address (ie slave is missing or sleeping).
This PR adds a check in the lasttx/lastrx wait loops to exit if an address NACK is received and return an `AddressNack` error.
Tested and verified to be working on nRF52840-DK

Fix Twim hangs on address NACK

---

Cargo.toml
examples/gpiote-demo/Cargo.toml
examples/gpiote-demo/Embed.toml
examples/gpiote-demo/src/main.rs
nrf-hal-common/src/gpiote.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/twim.rs

Hi nRF team!
Here's a starting point of a Gpiote module, based on how i've been using it in my projects.
Let's discuss a suitable api, at the moment it looks like this:
`let gpiote = gpiote::Gpiote::new(p.GPIOTE);`
Example how to configure an input pin as an event source for channel 0, triggering on hi-to-low transition and firing the GPIO interrupt:
`let btn1 = p0.p0_11.into_pullup_input().degrade();`
`gpiote.channel0().input_pin(&btn1).hi_to_lo().enable_interrupt();`
Or using port event:
`gpiote.port().input_pin(&btn1).low();`
`gpiote.port().input_pin(&btn3).low();`
`gpiote.port().enable_interrupt();`
In the GPIOTE ISR, check for triggered events like:
`gpiote.channel0().is_event_triggered()`
Reset channel events like:
`gpiote.channel0().reset_events();`
Reset port events like …

Add Gpiote module (open for feedback)

---

nrf-hal-common/Cargo.toml
nrf-hal-common/src/temp.rs

This PR moves the fixed point library to one that is stable, maintained and has better functionality.
This is a breaking change, but IMO a minor one.
The only blocker I can think of is that since the 1.0 release of the fixed crate, it requires rustc 1.44 or higher. I don't see a minimum version mentioned here in the HAL though.

Move to 'fixed' crate

---

nrf-hal-common/src/saadc.rs

Hey, props to you guys! This crate is really easy to add stuff in. (Well, so far at least 😉)
I missed the option for measuring the VDD voltage and all non-9160 mcu's support it.
So I added a struct and made the channel_mappings implement it for me.
The read function now checks for 'channel' 8 as well.

Added VDD source for the ADC

---

Cargo.toml
examples/comp-demo/Cargo.toml
examples/comp-demo/Embed.toml
examples/comp-demo/src/main.rs
nrf-hal-common/src/comp.rs
nrf-hal-common/src/lib.rs

Added a HAL module for the `COMP` analog comparator peripheral.
The comparator compares an input voltage (Vin) against a second input voltage (Vref).
Vin can be derived from an analog input pin (AIN0-AIN7).
Vref can be derived from multiple sources depending on the operation mode of the comparator.
Tested on NRF52840-DK
Demo (nRF52840):
https://github.com/kalkyl/nrf-hal/blob/comp/examples/comp-demo/src/main.rs

Add COMP module

---

Cargo.toml
examples/qdec-demo/Cargo.toml
examples/qdec-demo/Embed.toml
examples/qdec-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/qdec.rs

Added a HAL module for the quadrature decoder peripheral.
Tested on NRF52840-DK with a Bourns PEC11R-4215F-S0024 rotary encoder
Demo of usage with rotary encoder triggering interrupt (nRF52840):
https://github.com/kalkyl/nrf-hal/blob/qdec/examples/qdec-demo/src/main.rs

Add QDEC module

---

Cargo.toml
examples/lpcomp-demo/Cargo.toml
examples/lpcomp-demo/Embed.toml
examples/lpcomp-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/lpcomp.rs

Added a HAL module for the LPCOMP low power comparator peripheral.
In System ON, the LPCOMP can generate separate events on rising and falling edges of a signal, or sample the current state of the pin as being above or below the selected reference. The block can be configured to use any of the analog inputs on the device.
Additionally, the low power comparator can be used as an analog wakeup source from System OFF or System ON. The comparator threshold can be programmed to a range of fractions of the supply voltage or to use an external analog reference input pin.
Tested on nRF52840-DK
Demo showing "analog power up" usage and interrupt triggering/reading comparator state:
https://github.com/kalkyl/nrf-hal/blob/lpcomp/examples/lpcomp-demo/src/main.rs

Add LPCOMP module

---

Cargo.toml
examples/twim-demo/Cargo.toml
examples/twim-demo/Embed.toml
examples/twim-demo/src/main.rs
examples/twis-demo/Cargo.toml
examples/twis-demo/Embed.toml
examples/twis-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/twis.rs

Added a HAL module for TWIS (I2C compatible two-wire interface peripheral, formerly referred to as an "I2C slave")
Here's a demo showing read and write operations using interrupts and multiple I2C addresses (ItsyBitsy nRF52840):
https://github.com/kalkyl/nrf-hal/blob/twis/examples/twis-demo/src/main.rs
Also added a TWIM demo that can also be used together with the above TWIS demo, to show the corresponding controller code (nRF52840-DK):
https://github.com/kalkyl/nrf-hal/blob/twis/examples/twim-demo/src/main.rs

Add TWIS module

---

Cargo.toml
examples/pwm-demo/Cargo.toml
examples/pwm-demo/Embed.toml
examples/pwm-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/pwm.rs

Added a HAL module for the PWM peripheral
LED demo of some different modes and features (nRF52840-DK):
https://github.com/kalkyl/nrf-hal/blob/pwm/examples/pwm-demo/src/main.rs

Add PWM module

---

Cargo.toml
examples/i2s-controller-demo/Cargo.toml
examples/i2s-controller-demo/Embed.toml
examples/i2s-controller-demo/src/main.rs
examples/i2s-peripheral-demo/Cargo.toml
examples/i2s-peripheral-demo/Embed.toml
examples/i2s-peripheral-demo/src/main.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/lib.rs

Added a HAL module for the I2S peripheral
Audio (Morse code) demo for I2S in "controller mode" (formerly referred to as "I2S master"),
transmitting audio signals to a DAC:
https://github.com/kalkyl/nrf-hal/blob/i2s/examples/i2s-controller-demo/src/main.rs
Tested on nRF52840-DK with a UDA1334a DAC
...or connect it to the...
"Peripheral mode" (formerly referred to as "I2S slave") demo,
using an RGB LED (APA102) to display the RMS level of the received I2S audio signal:
https://github.com/kalkyl/nrf-hal/blob/i2s/examples/i2s-peripheral-demo/src/main.rs
Tested on ItsyBitsy nRF52840 with its onboard RGB LED

Add I2S module

---

nrf-hal-common/build.rs

This currently fails with a not-so-obvious linker error from the cortex-m-rt linker script, since the chips have more than 32 interrupts (the limit of thumbv6).

Refuse to build nRF52+ HALs for thumbv6

---

examples/spi-demo/src/main.rs
nrf-hal-common/src/spim.rs

It was deprecated a while ago. Breaking change.

Remove `Spi::read`

---

examples/i2s-controller-demo/src/main.rs
examples/i2s-peripheral-demo/Cargo.toml
examples/i2s-peripheral-demo/src/main.rs
nrf-hal-common/Cargo.toml
nrf-hal-common/src/i2s.rs

I changed the I2S module to use a DMA `Transfer` API for TX and RX operations.
I also added support for full duplex transfers and the demos were updated according to the new API.
"Controller mode" demo (TX):
https://github.com/kalkyl/nrf-hal/blob/i2s-dma/examples/i2s-controller-demo/src/main.rs
"Peripheral mode" demo (RX):
https://github.com/kalkyl/nrf-hal/blob/i2s-dma/examples/i2s-peripheral-demo/src/main.rs

Use DMA Transfer API in I2S module

---

nrf-hal-common/src/ppi/mod.rs
nrf-hal-common/src/ppi/task_nrf52832.rs

This adds channel groups to the ppi::Parts for accessing the PPI channel group tasks.

PPI channel group tasks

---

nrf-hal-common/src/lib.rs
nrf51-hal/Cargo.toml
nrf51-hal/src/lib.rs
nrf52810-hal/Cargo.toml
nrf52810-hal/src/lib.rs
nrf52832-hal/Cargo.toml
nrf52832-hal/src/lib.rs
nrf52833-hal/Cargo.toml
nrf52833-hal/src/lib.rs
nrf52840-hal/Cargo.toml
nrf52840-hal/src/lib.rs
nrf9160-hal/Cargo.toml
nrf9160-hal/src/lib.rs
xtask/src/lib.rs
xtask/src/main.rs
xtask/tests/ci.rs

This can be used to automatically bump all crate versions, as well as the changelog version, to the specified version, which reduces the work to publish a new version of the HAL.
Closes #198 (I've added `html_root_url` and it is now automatically updated)

Implement `cargo xtask bump` for bumping versions

---

CHANGELOG.md
nrf-hal-common/src/gpiote.rs

The Configuration of the GPIOTE needs the Port to be set (on devices
with multiple ports)
This resolves #216 .
Signed-off-by: trembel <silvano.cortesi@hotmail.com>

Adding Port on GPIOTE Configuration

---

nrf-hal-common/src/saadc.rs
xtask/tests/ci.rs

Extends the SAADC documentation with an example and some info on trait impls and default values.

saadc.rs: add documentation

---

CHANGELOG.md
examples/spis-demo/Cargo.toml
examples/spis-demo/Embed.toml
examples/spis-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/spis.rs
xtask/src/lib.rs

Added a module for the SPIS peripheral, using the `embedded-dma` traits.
Tested on nRF52840.
Demo of usage (pinout is for the ItsyBitsy nRF52840):
https://github.com/kalkyl/nrf-hal/blob/spis/examples/spis-demo/src/main.rs

Add SPIS module

---

README.md

The links to the product specifications were out of date on multiple devices. These have been updated and I have added links to the devices DK references guides as well. Formatted in a table with links shown as version numbers so it is clear what version the README is linking too.

Update Product Specification links and add DK Reference Guide links

---

nrf-hal-common/src/spis.rs

We need + 'static on the `WriteBuffer`/`ReadBuffer` bounds

Add 'static lifetime bounds to SPIS DMA buffers

---

nrf-hal-common/src/timer.rs

This PR adds task- and event endpoint getters to the Timer module so the timers can be used with PPI.

Add Timer task/event endpoint getters for PPI

---

nrf-hal-common/src/ppi/mod.rs

This allows to create nice generic driver APIs with `impl ConfigurablePpi` arguments
Example:
```` rust
fn link_pins(
gpiote: &hal::gpiote::Gpiote,
mut ppi: impl ConfigurablePpi,
out_pin: Pin<Output<PushPull>>,
in_pin: Pin<Input<PullUp>>,
) {
// ...
}
`````

Make `ConfigurablePpi` a subtrait of `Ppi`

---

nrf-hal-common/src/twim.rs

- Derive Copy, Clone, Eq, PartialEq for Error
- Disallow zero-length buffers, fixes #208 
- Handle all errors. Previously only AddressNack was handled, and the transfer would hang if another error ocurred.
- remove chunking in `copy_write_then_read`.  The previous implementation would send a TWI start condition for each chunk, so the slave chip would see each as a separate transaction. This is not equivalent to `write_then_read`, which was the original goal of adding chunking. It seems TWIM has no way to send multiple buffers in a single transaction, therefore the ability to chunk is removed.
There are some issues left with TWIM:
- There's no way for the user use SUSPEND manually if they want to do a more complex repeated start sequence. Nordic's lib has a "hold" flag that suspends …

TWIM improvements.

---

nrf-hal-common/src/gpio.rs
nrf-hal-common/src/twim.rs

This adds a `conf()` utility function to get the pin's config register.
Slight code duplication reduction :)

gpio: add conf() utility function.

---

nrf-hal-common/src/pwm.rs
nrf-hal-common/src/rtc.rs
nrf-hal-common/src/spi.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/twi.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/twis.rs
nrf-hal-common/src/uart.rs
nrf-hal-common/src/uarte.rs

🦭 all Instance traits

---

CHANGELOG.md
nrf-hal-common/src/gpio.rs
nrf-hal-common/src/uarte.rs

Return ownership of the pins back to the user when calling `free()`
Useful to multiplex a single USARTE instance to multiple serial connections on different pins (for smaller NRF52 devices which only have one USARTE instance).
Alternative: Only take a reference to the pins in in `new()`.
Please let me know which one is the preferred approach.

Also release owned `Pins` with `Usart::free()`

---

nrf-hal-common/src/twim.rs

When a new TWIM instance is created, it is automatically enabled. This is very convenient in normal use. For a low power sensor, I found myself in the situation that I needed to deactivate (and later reactivate) the instance in order to safe energy. The simplest way I found to do this, was to add the "enable" and "disable" functions to the instance.
Please let me know, whether you would like to integrate this change into the main branch.

Enabling and disabling the TWIM instance

---

CHANGELOG.md

Wording is by @jonas-schievink (in the Matrix channel), I thought it was a good explanation and copied it 1:1 :slightly_smiling_face: 
Also, I removed the emoji. Even though they're cute, they're hard to recognize and understand by non-native English speakers and by visually impaired people.

CHANGELOG: Explain what sealing means

---

nrf-hal-common/src/twim.rs

Adds TWIM1 to TWIM3 for the nrf9160.

Add TWIM1-3 for nrf9160

---

nrf-hal-common/src/twim.rs

This fixes TWIM initialization for the nRF52833. (I'm not clear whether any other non-nRF52840 variants need this change or not.)

Fix TWIM pin selection for nRF52833

---

nrf-hal-common/src/uarte.rs

From reading the code, it seems to me that the wrong error code is returned when the provided rx_buffer u8::max size check fails.

Return correct error code in uarte start_read

---

nrf-hal-common/src/gpiote.rs

I updated the write commands and the comments. I tested the code by setting two interrupts on a nRF52810.

Fix #277 (re)setting GPIOTE interrupts for channels

---

nrf-hal-common/src/lib.rs
nrf-hal-common/src/wdt.rs

Small changes to make WDT work on the nRF9160.
Tested on my hardware (Actinius Icarus):
* set_lfosc_ticks
* activate
* try_recover
* pet

Adding WDT to nRF9160.

---

nrf-hal-common/src/ppi/mod.rs

Add a function to clear the fork task endpoint of a PPI channel.
Nordic's docs are not very explicit on whether writing 0 to the `FORK[n].TEP` register is allowed. However nrfx's docs do say it's possible: https://github.com/NordicSemiconductor/nrfx/blob/d779b49fc59c7a165e7da1d7cd7d57b28a059f16/drivers/include/nrfx_ppi.h#L118

ppi: add clear_fork_task_endpoint

---

nrf-hal-common/src/uarte.rs

Seems like this was overlooked and still checks against `u8::max_value()`

uarte: check rx buf against EASY_DMA_SIZE

---

nrf-hal-common/src/gpio.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/qdec.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/spis.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/twis.rs
nrf-hal-common/src/uarte.rs

Moves the scattered `#[cfg()]` to a single place in the gpio module.

Refactor Pin Selection and Reconstructions

---

nrf-hal-common/src/saadc.rs

Support using vddhdiv5 as a source to the saadc.

Support vddhdiv5 for saadc

---

nrf-hal-common/src/saadc.rs

Without this, if you initialize SAADC for a second time, the events_calibratedone is still set from before, so the while loop doesn't wait for calibration to be done. This causes garbage readings if you read immediately after, because calibration is still running.

saadc: Clear events_calibratedone before calibration

---

nrf52840-hal/src/ieee802154.rs
nrf52840-hal/src/lib.rs

what the title says
this PR adds an `ieee802154::Radio` API that wraps the `RADIO` peripheral and puts it in IEEE 802.15.4 mode.
I haven't checked the silicon erratas of (or tested) other chips (the code contains one workaround for (nRF52840 specific?) silicon errata) so for now I have put the API directly under `nrf52840-hal`. But I guess the API should also work on other nRF52 devices -- I think the nRF51 chips do not have an 802.15.4 mode? And I don't know about other chip families.
The implementation is not super IEEE compliant. It's missing a backoff delay mechanism when doing CCA (Clear Channel Assessment) before transmitting packets and it's also missing IFS (inter-frame spacing) between consecutive packets (the hardware has some built-in support for this but the PR doesn't expose …

initial ieee802.15.4 API

---

nrf-hal-common/src/ieee802154.rs

I noticed that this info is documented for `ieee802154::recv()` but not for `recv_timeout`. This PR fixes that :)

recv_timeout(): document that received data is written to `packet` on return

---

examples/pwm-blinky-demo/Cargo.toml
examples/pwm-blinky-demo/src/main.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/pwm.rs

It compiles cleanly, except for the PAC missing fields for the tasks registers. Replaced those with `.bits(1)`, which works on all chips.
Untested on hardware as I don't have a nrf52832 at hand.

Enable PWM for nrf52832

---

nrf-hal-common/src/uarte.rs

See ttps://github.com/NordicSemiconductor/nrfx/blob/master/drivers/src/nrfx_uarte.c#L197

Apply the UARTE workaround for nrf91 and nrf53

---

examples/hello-world/Cargo.toml
examples/hello-world/Embed.toml
examples/hello-world/src/main.rs
xtask/src/lib.rs

Provides the simplest example of using UART for both the 52840 and 9160.
Tested successfully on:
* nrf52840-dk
* nrf9160-dk
* Thingy:91 (having modified the GPIO pins locally)

Uart example

---

examples/rtc-demo/src/main.rs

I find it common to use an interrupt with RTC so I've enhanced this example to illustrate how an interrupt can be established and managed.

Enhances the RTC example with an interrupt

---

CHANGELOG.md
nrf-hal-common/src/twis.rs

Noticed there was a mistake in the `Transfer`  `is_done()` of the TWIS module, it always returns true.

Fix TWIS is_done() always returns true

---

CHANGELOG.md
nrf-hal-common/src/spis.rs

Noticed there was a mistake in the `Transfer` impl of `is_done()` where it would `take()` `inner` instead of `as_mut()`.

Fix SPIS Transfer is_done() mistake

---

examples/pwm-blinky-demo/src/main.rs
examples/pwm-demo/src/main.rs
nrf-hal-common/src/gpio.rs
nrf-hal-common/src/pwm.rs

Fixes https://github.com/nrf-rs/nrf-hal/issues/320 by taking the pin by-value (cc @Dirbaio)
To allow the same flexibility as before, this adds `swap_output_pin`, which returns the old pin (though I haven't tested this API).

Fix `Pwm::set_output_pin` soundness, add `swap_output_pin`

---

.gitignore
examples/nvmc-demo/Cargo.toml
examples/nvmc-demo/Embed.toml
examples/nvmc-demo/build.rs
examples/nvmc-demo/memory.x
examples/nvmc-demo/src/main.rs
nrf-hal-common/Cargo.toml
nrf-hal-common/src/lib.rs
nrf-hal-common/src/nvmc.rs
nrf52840-hal-tests/Cargo.toml
nrf52840-hal-tests/README.md
nrf52840-hal-tests/build.rs
nrf52840-hal-tests/memory.x
nrf52840-hal-tests/tests/nvmc.rs
xtask/src/lib.rs

The [embedded-storage](https://github.com/rust-embedded-community/embedded-storage) traits are implemented to provide a higher-level abstraction for reading and writing from/to flash storage. In the first instance, support is provided for the nRF52 boards and the nRF9160, but other boards should be relatively easy to support if required in the future.
Sample usage of writing to flash given some 32 bit aligned slice of bytes:
```rust
// Erase a page
let _ = nvmc.try_erase(0, 4096);
// Write the 32 bit aligned slice
let _ = nvmc.try_write(0, some_u8_slice_on_32_bit_bounds);
```
An example of establishing the `Nvmc` on the nRF9160:
```rust
let mut nvmc = Nvmc::new(board.NVMC_NS, unsafe { &mut CONFIG });
```
...where CONFIG points to flash:
```rust
extern "C" {
#[link_name = "_config"]
static …
```

Provides common Nvmc functionality

---

.vscode/settings.json

Followup to https://github.com/nrf-rs/nrf-hal/pull/338, this makes things work even when `rust-analyzer.cargo.allFeatures` is globally enabled.
bors r+

VS Code: don't enable all features

---

nrf-hal-common/src/lib.rs
nrf-hal-common/src/spi.rs

This extends the `spi` implementation to all nRF52 devices.
Some features-based conditionals are required as those devices
have some slightly different register names and a varying amount
of supported interfaces.
Manually tested locally on a nRF52840 only.

common/spi: add support for all nRF52 devices

---

nrf-hal-common/src/uarte.rs

Since #281 has been abandoned by the author this is a continuation of his work in a seperate PR.

 Add embedded_hal::serial implementation for uarte (continuation)

---

nrf-hal-common/src/ieee802154.rs

ieee802154: automatically disable radio after tx

---

nrf52840-hal-tests/Cargo.toml

Apparently the old version is now causing dependency resolution problems in https://github.com/nrf-rs/nrf-hal/pull/364
bors r+

Update defmt crates

---

nrf-hal-common/src/gpio.rs

I ran into this when needing to take a generic struct that could contain any gpio pin. Since all the gpio pins have a degrade function I see no reason to not implement `From`. This allows generic code to work better.

Add From impl for pins

---

Cargo.ci.toml
nrf-hal-common/Cargo.toml
nrf-hal-common/src/clocks.rs
nrf-hal-common/src/comp.rs
nrf-hal-common/src/gpio.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/nvmc.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/rtc.rs
nrf-hal-common/src/saadc.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/spis.rs
nrf-hal-common/src/timer.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/twis.rs
nrf-hal-common/src/uarte.rs
nrf-hal-common/src/wdt.rs
nrf5340-app-hal/Cargo.toml
nrf5340-app-hal/README.md
nrf5340-app-hal/build.rs
nrf5340-app-hal/memory.x
nrf5340-app-hal/src/lib.rs
xtask/src/lib.rs

This PR adds a HAL for the nRF5340's app core. It is more or less identical to the nRF9160 HAL that already exists, with some features added or removed for the nRF5340. I have not added support for the net core yet, as I don't need it for my use case.

Add nrf5340-app-hal

---

nrf-hal-common/src/ieee802154.rs

after PR #356 the radio is disabled after every `send` operation.
if one calls `recv` immediately after `send`, `recv` can observe the radio in the TXDISABLE state
TXDISABLE is a transitory state that leads to the final DISABLED state which the impl knows how to handle
this PR adds logic to handle the transitory TXDISABLE state
fixes #368
---
I have checked that the programs in https://github.com/ferrous-systems/embedded-trainings-2020 work again with this change

ieee802154: handle the transitory state TXDISABLE

---

nrf-hal-common/src/nvmc.rs

This PR implements `MultiwriteNorFlash` as suggested [here](https://github.com/nrf-rs/nrf-hal/issues/336#issuecomment-878684844).
I only listed nRF52 boards that support writing twice to the same word, because I'm not familiar with the other boards or crate features.

Implement MultiwriteNorFlash for nRF52 boards that support it

---

CHANGELOG.md
examples/i2s-controller-demo/src/main.rs
examples/i2s-peripheral-demo/src/main.rs
examples/qdec-demo/src/main.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/qdec.rs
nrf-hal-common/src/spi.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/spis.rs
nrf-hal-common/src/twi.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/twis.rs
nrf-hal-common/src/uart.rs
nrf-hal-common/src/uarte.rs
nrf52840-hal-tests/tests/gpio-output-open-drain.rs
nrf52840-hal-tests/tests/serial.rs

Hi,
I unified so pins are returned the same for all peripherals.

Unified how pins are return in `free` calls

---

examples/nvmc-demo/Cargo.toml
examples/nvmc-demo/memory.x
examples/nvmc-demo/src/main.rs
nrf-hal-common/src/nvmc.rs
nrf52840-hal-tests/memory.x
nrf52840-hal-tests/tests/nvmc.rs

This PR opens a design discussion regarding the Nvmc API and implementation.
It contains the following 3 commits:
1. Modify the example to surface some of the following issues:
- Bug: [`new`](https://github.com/nrf-rs/nrf-hal/blob/bcd5c5da6e5087b7efd943806ec599d42b5e2c3f/nrf-hal-common/src/nvmc.rs#L28) doesn't check that the storage is well-aligned.
- Bug: [`read`](https://github.com/nrf-rs/nrf-hal/blob/bcd5c5da6e5087b7efd943806ec599d42b5e2c3f/nrf-hal-common/src/nvmc.rs#L112) confuses offsets in the storage and offsets in the output buffer.
- Bug: Many arithmetic overflows like [here](https://github.com/nrf-rs/nrf-hal/blob/bcd5c5da6e5087b7efd943806ec599d42b5e2c3f/nrf-hal-common/src/nvmc.rs#L106)
- Bug: [Off-by-one error](https://github.com/nrf-rs/nrf-hal/blob/bcd5c5da6e5087b7efd943806ec599 …

Improve Nvmc implementation of embedded-storage traits

---

README.md
examples/README.md
xtask/tests/ci.rs

Largely avoids https://github.com/nrf-rs/nrf-hal/issues/375, just the license file links are broken now.
bors r+

Split readme and avoid most broken links

---

nrf-hal-common/src/nvmc.rs

per the product specification [section 4.4](https://infocenter.nordicsemi.com/pdf/nRF9160_PS_v2.0.pdf#page=29) there can be n_write writes, where `t_write = 2` [source](https://infocenter.nordicsemi.com/pdf/nRF9160_PS_v2.0.pdf#page=35). Unless I'm missing something, that means that the contract of `MultiWriteNorFlash` is satisfied.

implement MultiWriteNorFlash for the nrf9160

---

CHANGELOG.md
nrf-hal-common/src/nvmc.rs

A byte offset was given where a word offset was required (factor 4 difference)

Fixed nvms erase problem for nrf91 & nrf53

---

nrf-hal-common/src/saadc.rs

Add a method to disable the Saadc and regain the inner pac-level peripheral handle

Add free method to Saadc

---

nrf-hal-common/src/uarte.rs

`Uarte::free` method uses `bit_is_set` to determine whether a pin was connected to `cts` and `rts`. However, a set bit represents a disconnected pin. Use `is_connected()` instead to do the inversion.

Use `is_connected` to determine whether a ctx/rtx was connected to uarte

---

examples/README.md

Inspired by https://github.com/nrf-rs/nrf-hal/issues/60 (but not resolving it fully, probably), this adds text to the general examples README on alternatives to the `cargo embed` process described in the individual READMEs.
This might need a few more items on the list based on the methods listed in #60; I'll be asking there to state which methods are still relevant. (To me, only copying is relevant, as that's what works without going through the process of unlocking the AP lock that is engaged on the nrf42dk board).

README: Mention USB copying of Hex files

---

nrf-hal-common/src/gpio.rs

As already reported in https://github.com/nrf-rs/nrf-hal/issues/339, there is currently no way to create an I/O pin in nrf-hal.
There are several reasons why having this would be useful. My personal usecase is the DHT22/AM2302 sensor. Controlling it requires a single-wire pulled-up open drain IO.
Sadly, this means that all libraries that can interface with it [require `InputPin + OutputPin`](https://docs.rs/dht-sensor/0.2.1/dht_sensor/trait.InputOutputPin.html).
There is no inherent reason why nrf chips shouldn't be able to implement this. The input buffer is always available and allows reading back the pin values during every pin configuration. Although for energy saving reasons, the input buffer is currently disabled during the `OpenDrain` state.
My proposal is to add an `OpenDrainIO` …

Add OpenDrainIO pin state (with InputPin capability)

---

nrf52840-hal-tests/Cargo.toml
nrf52840-hal-tests/tests/gpio-output-open-drain-io.rs

- Add tests for `OpenDrainIO`
- Added in #401
- Add missing test for `OpenDrain`

Add missing OpenDrain[IO] tests

---

examples/i2s-peripheral-demo/src/main.rs
examples/spi-demo/src/main.rs
nrf-hal-common/src/spim.rs

Followup to https://github.com/nrf-rs/nrf-hal/pull/400 to make the APIs match again
bors r+

SPIM: make SCK optional to match SPI

---

nrf-hal-common/src/i2s.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/qdec.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/spis.rs

Applies https://github.com/nrf-rs/nrf-hal/pull/397 to the whole HAL.
bors r+

Change all psel tests to use `is_connected`

---

nrf5340-app-hal/Cargo.toml
nrf9160-hal/Cargo.toml

These 2 have a more specific readme than the repository-wide one, and `cargo publish` warns about the link in the `Cargo.toml`.
bors r+

Point 2 HALs to their own readme

---

nrf-hal-common/src/i2s.rs

This is embarrassing. It appears my quality assurance for #412, while existent, was way flawed and insufficient.
Having a `try_` method take ownership over self makes it impossible call it more than once. Clearly a mutable reference was what was indented and required to actually make the method meaningful.
It would be a good idea to either merge this PR, or revert the previous one, prior to making the next release.

Correct eb3b96b with a useful function signature for try_wait

---

nrf-hal-common/src/gpio.rs

The nRF GPIO output pins support a "high drive" mode for low and high push-pull outputs individually. A high-drive output can source more current, and thus has a faster transition than "standard drive". I needed this for experimenting with the MicroBit v2 speaker output pin.
Right now, this crate supports only "standard drive" push-pull outputs. This non-breaking pull request add an `.into_push_pull_output_drive()` method to pins, with an extra configuration argument `DriveConfig`. This is kind of gross, but was chosen to avoid changing `.into_push_pull_output()`.
I would be happy to add tests, but would need some tutoring to understand exactly how. Bikeshedding is also quite welcome.

Add method for controlling GPIO push-pull output drive

---

nrf-hal-common/src/timer.rs

The docs for `nrf-hal-common::timer` reported a lot of warnings when running : 
```bash
cargo doc
```
This PR aims to resolve these warnings by escaping all of the brackets in that file.

fix doc comments, remove warnings when running cargo doc

---

nrf-hal-common/Cargo.toml
nrf-hal-common/src/adc.rs
nrf-hal-common/src/delay.rs
nrf-hal-common/src/gpio.rs
nrf-hal-common/src/ieee802154.rs
nrf-hal-common/src/lib.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/saadc.rs
nrf-hal-common/src/spi.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/timer.rs
nrf-hal-common/src/twi.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/uart.rs
nrf-hal-common/src/uarte.rs

Now that `embedded-hal` 1.0 is released, this PR adds implementations of most of its relevant traits. For now I've added them alongside the existing `embedded-hal` 0.2 trait implementations, so that users can still use drivers based on the old traits. We can remove the old traits in a later release.
I haven't implemented the `embedded-hal-nb` and `embedded-hal-async` traits yet, and the I2C traits are also missing as the design has changed and implementing it correctly is non-trivial.

Implement embedded-hal 1.0 traits

---

nrf-hal-common/src/adc.rs

`Channel` isn't a sealed trait, so we can't assume that the implementation is correct. It's better to panic than have undefined behaviour.

Panic if Channel::channel() returns an invalid value.

---

.github/dependabot.yml

There is no cargo workspace checked in, so dependabot treats each crate separately.

Configure dependabot per directory.

---

nrf-hal-common/src/lib.rs

The latest Rust 1.80 generates a warning for a reference to `cfg(feature = "52820")`, which is not currently a thing — for some reason there is not yet an `nrf52820-hal` crate. This warning gets turned into a failure in CI.
"Fixed" by commenting out the offending code.

fixed 52820 config warning

---

nrf-hal-common/src/pwm.rs

Recent Rust warns about unnecessary `unsafe` wrapping `addr_of_mut!()`. Suppress these warnings for now.

hid unecessary unsafes in pwm.rs for back compatibility

---

nrf-hal-common/src/spi.rs

The code was ignoring the pin ports and always using port0.

Use correct port for SPI on 52xxx

---

nrf-hal-common/src/ccm.rs
nrf-hal-common/src/gpio.rs
nrf-hal-common/src/gpiote.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/ieee802154.rs
nrf-hal-common/src/nvmc.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/saadc.rs
nrf-hal-common/src/spim.rs
nrf-hal-common/src/spis.rs
nrf-hal-common/src/time.rs
nrf-hal-common/src/twim.rs
nrf-hal-common/src/uarte.rs

Fixed a bunch of long-standing clippy and rustfmt issues in nrf-hal-common in a minimally-intrusive fashion.

fixed clippy and rustfmt warnings in nrf-hal-common
