nrf-rs/nrf-hal

boards/adafruit_nrf52pro/examples/blinky.rs
nrf52-hal-common/src/gpio.rs

I've requested review from @jscarrott, since he said he he wanted to work on GPIO this weekend, but of course everyone else is also welcome to review/merge this. I'd appreciate a close look at the open-drain commit, as I might have misunderstood something there.
@jscarrott, I'm sorry for making the GPIO code more complicated before you wanted to look into refactoring it. If this turns out to be a problem, feel free to disregard this for now. I'm happy to rebase this pull request later on top of your work.

Make improvements to GPIO

---

nrf52-hal-common/src/delay.rs

Correct behavior of SysTick timer

---

nrf52-hal-common/src/timer.rs
nrf52-hal-common/src/uarte.rs

Closes #42, also adds RX functionality with optional timeout to Uarte.
@hannobraun I'd be interested to hear your opinion on this approach for receiving with a fixed timeout.

Fix/Extend UARTE

---

nrf52-hal-common/src/uarte.rs

I did not implement the traits in `embedded_hal::serial` because I couldn't tell whether they're allowed to block (and their documentation didn't help).

Implement fmt::Write for Uarte

---

nrf52-hal-common/Cargo.toml
nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/temp.rs
nrf52810-hal/src/lib.rs
nrf52832-hal/src/lib.rs
nrf52840-hal/src/lib.rs

Virtually copy-pasted from @jonas-schievink's PR, https://github.com/nrf-rs/nrf51-hal/pull/17.

feat: add temperature interface

---

nrf52-hal-common/src/rng.rs

fix: enable RNG bias correction

---

nrf52-hal-common/src/clocks.rs

Sorry about the rustfmt changes. The important one is moving `stop_lfclk` into an impl for `Clocks<H, L, LfOscStarted`. This will allow the compiler to prevent stopping the clock when it's not started.

Do not allow stopping the Low Frequency clock when it's not started.

---

nrf52-hal-common/src/uarte.rs

I encountered a problem with the `read_timeout` function during the OxidizeConf workshop. When I passed it a four byte buffer two weird things could happen:
1) I send one byte which is received and put in the buffer, but the function returned `Err(Timeout(0))`
2) I send four bytes, correctly resulting in `Ok(())`, but from then on returning `Err(Timeout(4))` without having to send anything.
After reading through the nRF52832 datasheet it seems that an incomplete reception must be `STOPRX`ed and the `FLUSHRX`ed to cause the `RXD.AMOUNT` to be updated correctly.
This PR implements that sequence if the `ENDRX` event is not set / the timeout elapsed.
If you need any additional work done to this PR, just get in contact.

Correctly stop incomplete UARTE reception after timeout.

---

nrf52-hal-common/src/lib.rs
nrf52-hal-common/src/spim.rs

This code has not yet been tested, nor has it been checked for size regressions.

Retooling of the SPI code

---

boards/adafruit-nrf52-bluefruit-le/Cargo.toml
boards/adafruit_nrf52pro/Cargo.toml
boards/nRF52-DK/Cargo.toml
examples/rtfm-demo/Cargo.toml
examples/spi-demo/Cargo.toml
nrf52-hal-common/Cargo.toml
nrf52810-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52840-hal/Cargo.toml

Update versions further

---

.travis.yml
boards/adafruit-nrf52-bluefruit-le/Cargo.toml
boards/adafruit-nrf52-bluefruit-le/examples/blinky.rs
scripts/build.sh

This makes it easier to run the equivalent of a CI build locally. Also includes some fixes to unrelated issues that I found while doing this.

Create build script

---

nrf-hal-common/src/spim.rs

This could also be implemented for the 52833. CC @blueluna and #148

Add impls for spim3 on nrf52840

---

README.md

The nRF52833 also needs to be added before the next release, but the nRF51 HAL is already out...

Add nRF51 support to the readme

---

nrf51-hal/Cargo.toml
nrf52810-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52833-hal/Cargo.toml
nrf52840-hal/Cargo.toml
nrf9160-hal/Cargo.toml

These were just copy-pasta'd all over the HAL shims

Remove unnecessary dependencies

---

CHANGELOG.md
Cargo.toml
examples/ccm-demo/Cargo.toml
examples/ecb-demo/Cargo.toml
examples/ppi-demo/Cargo.toml
examples/rtfm-demo/Cargo.toml
examples/spi-demo/Cargo.toml
examples/twi-ssd1306/Cargo.toml
nrf51-hal/Cargo.toml

Did I miss anything?
Closes https://github.com/nrf-rs/nrf-hal/issues/59

Add a Changelog (+ a few Cargo.toml fixes)

---

nrf-hal-common/Cargo.toml

Updated the nb crate to the 1.0.0 release.
Updated the patch level for other crates as well (this has no effect for the crate though).

Updated dependencies

---

examples/blinky-button-demo/Cargo.toml
examples/blinky-button-demo/Embed.toml
examples/blinky-button-demo/README.md
examples/blinky-button-demo/src/main.rs
xtask/src/lib.rs

This PR adds a simple Blinky example that turns on an LED when you push a button.

Add Blinky button demo to the examples

---

nrf-hal-common/src/spis.rs

If `transfer` or `transfer_split` throws an error, you would lose the peripheral permanently.
In this PR, the returned Err variant gives you back the `Spis<T>` and the buffer(s) along with the `Error`, in tuple form.
So `transfer`now returns `Result<Transfer<T, B>, (Error, Spis<T>, B)>`
and `transfer_split` returns `Result<TransferSplit<T, TxB, RxB>, (Error, Spis<T>, TxB, RxB)>`
An alternative would be to put them inside the `Error` enum variants, but i reasoned this tuple pattern would be less cumbersome to work with in user code.

Return Spis and buffer(s) in transfer & transfer_split Err

---

nrf-hal-common/src/gpio.rs

Add `into_disconnected` to `Pin` and all `$PXi` structs.

gpio: add into_disconnected

---

nrf-hal-common/src/gpiote.rs

Add port for gpiote task output pins (52833/52840)

---

nrf-hal-common/src/twim.rs

Fix TWIM warnings

---

CHANGELOG.md
nrf-hal-common/src/ppi/mod.rs

Seal public PPI traits

---

CONTRIBUTING.md

This documents our release process, and provides some guidance for contributors

Add contribution and maintenance docs

---

CHANGELOG.md
nrf-hal-common/Cargo.toml
nrf-hal-common/src/lib.rs
nrf51-hal/Cargo.toml
nrf51-hal/src/lib.rs
nrf52810-hal/Cargo.toml
nrf52810-hal/src/lib.rs
nrf52811-hal/Cargo.toml
nrf52811-hal/src/lib.rs
nrf52832-hal/Cargo.toml
nrf52832-hal/src/lib.rs
nrf52833-hal/Cargo.toml
nrf52833-hal/src/lib.rs
nrf52840-hal/Cargo.toml
nrf52840-hal/src/lib.rs
nrf9160-hal/Cargo.toml
nrf9160-hal/src/lib.rs

Publish 0.12.1

---

README.md
nrf-hal-common/src/ccm.rs
nrf-hal-common/src/clocks.rs
nrf-hal-common/src/i2s.rs
nrf-hal-common/src/pwm.rs
nrf-hal-common/src/rtc.rs
nrf-hal-common/src/saadc.rs
nrf-hal-common/src/wdt.rs

Closes https://github.com/nrf-rs/nrf-hal/issues/303

Fix spelling errors + RTIC name

---

nrf-hal-common/src/ieee802154.rs

fixes https://github.com/nrf-rs/nrf-hal/issues/310
bors r+

ieee802154: mark `start_recv` as unsafe

---

nrf9160-hal/README.md
nrf9160-hal/memory.x

Also adds a README to explain why we need SPM.

Update 9160 HAL with latest memory map.

---

nrf-hal-common/Cargo.toml
nrf51-hal/Cargo.toml
nrf52810-hal/Cargo.toml
nrf52811-hal/Cargo.toml
nrf52832-hal/Cargo.toml
nrf52833-hal/Cargo.toml
nrf52840-hal/Cargo.toml
nrf9160-hal/Cargo.toml

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

Link README.md into all sub-crates so they show up on crates.io

---

CHANGELOG.md
nrf-hal-common/Cargo.toml
nrf-hal-common/src/lib.rs
nrf51-hal/Cargo.toml
nrf51-hal/src/lib.rs
nrf52810-hal/Cargo.toml
nrf52810-hal/src/lib.rs
nrf52811-hal/Cargo.toml
nrf52811-hal/src/lib.rs
nrf52832-hal/Cargo.toml
nrf52832-hal/src/lib.rs
nrf52833-hal/Cargo.toml
nrf52833-hal/src/lib.rs
nrf52840-hal/Cargo.toml
nrf52840-hal/src/lib.rs
nrf9160-hal/Cargo.toml
nrf9160-hal/src/lib.rs

Publish v0.12.2

---

examples/ccm-demo/Cargo.toml
nrf-hal-common/Cargo.toml

Update common dependencies

---

README.md

The footnote should not be part of the table
bors r+

Improve formatting of table in readme

---

nrf-hal-common/src/i2s.rs

Fixes https://github.com/nrf-rs/nrf-hal/issues/326 (untested)
cc @RuneKokNielsen

Fix I2S frequency mapping

---

CHANGELOG.md

Update changelog for 0.13

---

Cargo.ci.toml
Cargo.example.toml

Should avoid the CI failure in https://github.com/nrf-rs/nrf-hal/pull/369#issuecomment-1004038623
bors r+

Use the new Cargo resolver

---

CHANGELOG.md
nrf-hal-common/Cargo.toml
nrf-hal-common/src/lib.rs
nrf51-hal/Cargo.toml
nrf51-hal/src/lib.rs
nrf52810-hal/Cargo.toml
nrf52810-hal/src/lib.rs
nrf52811-hal/Cargo.toml
nrf52811-hal/src/lib.rs
nrf52832-hal/Cargo.toml
nrf52832-hal/src/lib.rs
nrf52833-hal/Cargo.toml
nrf52833-hal/src/lib.rs
nrf52840-hal/Cargo.toml
nrf52840-hal/src/lib.rs
nrf5340-app-hal/Cargo.toml
nrf5340-app-hal/src/lib.rs
nrf9160-hal/Cargo.toml
nrf9160-hal/src/lib.rs

Bump to 0.14.1

---

nrf-hal-common/src/gpiote.rs
nrf-hal-common/src/lib.rs

Title says it all
cc @diondokter

nrf9160 enable gpiote

---

nrf-hal-common/src/adc.rs

Adds channels for measuring VDD level on nrf51 ADC. Useful to monitor battery state if powered directly from 2 AA cells.

Add Internal VDD channels for nrf51 ADC

---

nrf-hal-common/src/spim.rs
nrf-hal-common/src/uarte.rs

Added impl statements for SPIM and UARTE interfaces for the nrf9160

added impl statements for SPIM and UARTE interfaces on nrf9160

---

nrf-hal-common/src/timer.rs

Added method to reset timer event flag.

added method to Timer trait for resetting event flag

---

nrf-hal-common/src/spi.rs

smart-leds-rs uses SPI without clock for controlling WS2812 LEDs.

Make SPI clock pin optional for use with WS2812

---

nrf-hal-common/src/i2s.rs

Wouldn't it be useful if being able to determine whether an I²S transfer has completed without busy looping?
The changes is this PR appears to be working for both `wait()` and `try_wait()`, but I must admit that the compiler fencing part flies a bit above my head even after refreshing myself on the topic. I'm actually preplexed of why it is needed in the first place. Is it to prevent buffer from being fetched for return prior to the loop being finished?
An implementation detail which might be questioned is whether `is_done()` is at all desired. My reasoning is that it reduces the code duplication slightly, and that adding it to the public api might be useful for someone. One could argue an extra function call adds overhead, but I am imagining the compiler would inline and optimize away …

Add is_done and try_wait methods to i2s::Transfer

---

nrf-hal-common/src/timer.rs

Add documentation for pub timer instances

Documentation for Timer Instance

---

nrf-hal-common/src/clocks.rs

Fix nRF51 HFCLK freq

---

examples/README.md
examples/blinky-button-demo/README.md
examples/rtc-demo/README.md

Update cargo-embed installation command following merge into probe-rs
